### PR TITLE
Servers in contracts

### PR DESCRIPTION
**Pull request by MarcusDunn**
This is my attempt at finishing off @zsambek's https://github.com/http4k/http4k/pull/510. There were some outstanding issues with https://github.com/http4k/http4k/pull/510 this PR hopefully resolves:
- rename ServerObject to ApiServer
- remove wildcard imports
- update examples
- add spec-compliant default
- change url type from `String` to `Uri`

I was uncertain on some formatting around when and where to make newlines for longer lines, let me know if there are any offensive formatting errors.

### CODE REVIEW

**Comment by daviddenton** [comment]
This all looks eminently sensible so far - let us know when it's done and we'll look at merging it! 😄

**Comment by MarcusDunn** [comment]
I don't think I can implement the servers defaults on the rendering side of things (as it it was in https://github.com/http4k/http4k/pull/674/commits/5768cb2aec07ee5c73e2932613813703473f255b). The Auto renderer simply rendered the empty list. I really dislike my current [code](https://github.com/http4k/http4k/pull/674/commits/ebf1485513845cd840f25175afc81b58f4d58e79#diff-1f6bdb4e8a15d84e00e1f0d65aedda191841722d8494676b673ba21f0184a7b8) to move the default behaviour to the `data class API`, I may just be missing an obvious solution. Are there examples of this type of default behaviour already?

**Comment by MarcusDunn** [comment]
@daviddenton I think this is ready from my end. From a standard-compliant completion perspective It's missing `variables` in [server-object/apiServer](https://swagger.io/specification/#server-object). But for my usecase, I do not need it and I imagine this is useful as a feature by itself to more people than just myself.

**Comment by daviddenton** [comment]
Thanks from picking this up: will try to look at it soon. 🙃

**Comment by daviddenton** [comment]
This will be released soon under 4.17.2.0. :)

**Pull request merged**
