### PR TITLE
Digest auth docs

### PR DESCRIPTION
**Pull request by oharaandrew314**

### CODE REVIEW

**Comment by daviddenton** [comment]
Thanks for the docs. 

We should also add the new module to the module index page and a reference to the functionality in the readme. 😉

**Comment by oharaandrew314** [comment]
Ah, thanks for the reminder.

**Comment by oharaandrew314** [comment]
Done.  It seems like the module overview page is generated from the top-level README, correct?

**Comment by daviddenton** [comment]
I was referring to this one: 

https://github.com/http4k/http4k/blob/master/src/docs/guide/reference/index.md

... but don't worry. I can easily add it. 🙃

**Comment by daviddenton** [comment]
FYI, I've also added the module to [https://toolbox.http4k.org](https://toolbox.http4k.org)

**Comment by oharaandrew314** [comment]
Cool.  Thanks!

**Pull request merged**
