### PR TITLE
Duplicated the classes from the underscore-java library

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
🌞

**Comment by daviddenton** [comment]
I'm a bit lost - what was the intended purpose of this change? 

It seems like we've just replaced a dependency with copying in some classes from that lib which we didn't write and would therefore need to maintain.

**Comment by javadev** [comment]
The classes are currently quite stable. The Kotlin classes seem to be more suitable for the library. It's worth noting that the library now has a dependency on Java 11.

**Comment by javadev** [comment]
➕

**Comment by s4nchez** [comment]
@javadev we're inclined to not include this change. 

As much as we want to minimize our dependencies, this module is meant to be used for testing purposes and it's hard to justify adding thousands of lines of code to our module, even though they may be stable.

**Comment by s4nchez** [comment]
We'll close this for now but can continue the discussion if needed.

**Pull request closed without merging**
