### PR TITLE
Bugfix: add nullsafety and fallback for description within the Status

### PR DESCRIPTION
**Pull request by Hakky54**
This PR fixes the following issue: https://github.com/http4k/http4k/issues/544

### CODE REVIEW

**Comment by s4nchez** [comment]
Thank you for the PR, @Hakky54 .

The null safety part seems ok. However, could we skip the fallback logic for now, please?

One of the http4k principles is trying to map request and response as "raw" as possible. This make troubleshooting integrations much simpler and forces behaviour to be always defined in filters, which are optional to library clients.

**Comment by Hakky54** [comment]
Sure, it makes the PR much simpler. I just removed it

**Comment by s4nchez** [comment]
Excellent, @Hakky54. Thank you again for the bug report and the PR.

We'll merge this and include in the next release.

**Comment by Hakky54** [comment]
Thank you very much for replying this quickly and approving the PR!

**Pull request merged**
