### PR TITLE
Added parameter TypeReference to Jackson writer in ConfigurableJackson.autoBody 

### PR DESCRIPTION
**Pull request by alphaho**
fix issue #313

### CODE REVIEW

**Comment by daviddenton** [comment]
Thanks for the PR. :) The change to the reader code seems legit - but I'm slightly worried that I don't understand the change in behaviour introduced in the 3rd commit (fb7be32). 

Is there a test you could write that shows the change in behaviour that would fail with the new version?

**Comment by alphaho** [comment]
Sorry for the confusion. For the 3rd commit (fb7be32), it's just to reuse the extension functions from the library Jackson Kotlin Module(by importing `com.fasterxml.jackson.module.kotlin.convertValue` and `readValue`). 

As I thought it would be a bit more readable to drop the anonymous object creation  `object : TypeReference<T>() {}`. 

These extension functions should not change the behavior as the calls are the same as before after inlined. And the original behavior should already be covered by `JacksonAutoTest`.

I'm happy to drop this commit if it causes too much confusion.

**Comment by daviddenton** [comment]
Ahh! I didn't spot those references. Thanks for clarifying!

**Comment by alphaho** [comment]
No worries, I should have pointed that out in the commit message/PR description.

**Pull request merged**
