### PR TITLE
WIP: migration to refreshVersions

### PR DESCRIPTION
**Pull request by jmfayard**
Don't merge yet, 

I'm using features who are not released
That's why the CI complains with `Could not find de.fayard.refreshVersions:refreshVersions:0.9.8-SNAPSHOT`

Development going on at https://github.com/jmfayard/refreshVersions/pull/245

### CODE REVIEW

**Comment by daviddenton** [comment]
this is amazing. Thanks for your efforts @jmfayard  😄

**Comment by daviddenton** [comment]
@jmfayard Thanks for taking this on. Apologies for you continually getting into conflict here - we've been busy!

Was just wondering if this is nearing a stage where we can merge it in - we'd like to do some more reoganising of the repo and don't want to cause you too much additional grief!

**Comment by jmfayard** [comment]
@daviddenton 
you can reorganize the repo, no problem

**Comment by daviddenton** [comment]
we're done with the repo reorg. hopefully you won't encounter too much pain if you rebase your fork.

**Pull request closed without merging**
