### PR TITLE
Added Freemarker as a templating engine.

### PR DESCRIPTION
**Pull request by amcghie**

### CODE REVIEW

**Comment by daviddenton** [comment]
That's awesome. Thank you VM!

Planning a new release v soon so it will go out ASAP.

**Comment by daviddenton** [comment]
This is now released as a part of 3.116.0.

**Comment by daviddenton** [comment]
This is now released as a part of 3.116.0, but we haven't got it added to jcenter yet. Until that happens (is could be a couple of days), you can get the module from the http4k repo at https://dl.bintray.com/http4k/maven

**Comment by amcghie** [comment]
Thanks @daviddenton

**Pull request merged**
