### PR TITLE
Basic Credentials Improvements

### PR DESCRIPTION
**Pull request by oharaandrew314**
- New `Header.AUTHORIZATION_BASIC` lens
- New `StringBidiMappings.basicCredentials`
- `BasicAuthSecurity` now supports `RequestContextLens`

### CODE REVIEW

**Comment by daviddenton** [comment]
let me know when is good and will merge it :)

**Comment by oharaandrew314** [comment]
Yes, sorry.  Tweaking pull requests is a terrible habit of mine.

**Comment by oharaandrew314** [comment]
I want to make sure the build passes first; the entire test suite doesn't work on my windows PC, due to the line endings in the approval tests.

**Comment by oharaandrew314** [comment]
@daviddenton the latest code-changing builds is passing, and I'm ready to have it merged.  I took the liberty of updating the changelog as you've suggested in the past, but I'm not sure if I did the right thing by assuming the next release version 🤷 .

**Comment by daviddenton** [comment]
nope - you did a good job with that. It's: <marketing>.<breaking>.<feature>.<bug>

The only thing you didn't do was HatTip yourself :)

**Pull request merged**
