### PR TITLE
feat(openApi3): remove oneOf when not needed

### PR DESCRIPTION
**Pull request by Stefanqn**
trim() in Approver was added due to default empty newline at EOF on Linux

### CODE REVIEW

**Comment by daviddenton** [comment]
@Stefanqn if you can get this passing then will merge 😄

**Comment by Stefanqn** [comment]
```
* What went wrong:
Execution failed for task ':http4k-core:test'.
> There were failing tests. See the report at: file:///home/runner/work/http4k/http4k/http4k-core/build/reports/tests/test/index.html
```
It seems unrelated to my changes. Apparently, it's something with the build tokens: https://github.com/mikepenz/action-junit-report/issues/23

**Comment by daviddenton** [comment]
It failed again on the same test: 

```
> Task :http4k-core:test

RoutePrintingTest > describe matching(Approver) FAILED
    java.lang.AssertionError at RoutePrintingTest.kt:49

RoutePrintingTest > describe routes(Approver) FAILED
    java.lang.AssertionError at RoutePrintingTest.kt:39
```

Does that all work locally on your machine?

**Comment by Stefanqn** [comment]
* @daviddenton no, sorry - I was distracted by the other error message.
* I fixed the tests, which failed due to trimming. Actually I removed a leading newline in the description result.
* I also had to fix tests related to the client IP. They failed, because on my linux machine `getLoopbackAddress` and `getLocalHost`  return different addresses.

**Comment by Stefanqn** [comment]
@daviddenton ok, should work now.

**Pull request merged**
