### PR TITLE
Support method not allowed

### PR DESCRIPTION
**Pull request by jshiell**
At present the route-matching is boolean, i.e. a route either matches or it doesn't. This results in a 404 being served for all unmatched requests.

This PR changes the routing so that it returns a match object, allowing us to differentiate on match failures. At this point it represents three states - `matched`, `path matched, method mismatched`, `unmatched`. The result is that we can now support returning 405 where the path is matched but the supported methods differ.

This is a breaking change, as the `Router.match` signature is now `fun match(request: Request): RouterMatchResult`, rather than returning `HttpHandler?`.

Given the scope of this change there's no way I'm merging it without a sanity check 😄

### CODE REVIEW

**Comment by jshiell** [comment]
Poke poke @daviddenton or @s4nchez 😄

**Comment by daviddenton** [comment]
I'm merged this into it's own branch so I can have a good looksee

**Comment by daviddenton** [comment]
BTW @jshiell your import settings are a bit *'y :)

**Comment by jshiell** [comment]
My import settings are the default, life's too short for such shit 😁

**Comment by daviddenton** [comment]
No more PRs from you if you don’t fix it!!

;p

**Pull request merged**
