### PR TITLE
Update 'Your first http4k app' tutorial

### PR DESCRIPTION
**Pull request by szmoon**
While working through the `Your first http4k app` tutorial, I found a few areas that might benefit from an update or addition and wanted to contribute back to this really helpful resource. These updates included:
- Including the command to utilize the http4k project wizard, as an alternative to using the web version (I had trouble locating an example for this, but figured it out from the http4k command options)
- Updating two incorrect paths (`/main` to `/test`)
- Adding the `/pong` endpoint manually in Step 6. Since the tutorial already led the reader to pointing the client at the `/pong` endpoint to see the 404, I thought it was a great opportunity to have the reader manually add the endpoint in (especially since the initial one was pre-populated by the project wizard

### CODE REVIEW

**Comment by daviddenton** [comment]
Thank you for the suggestions! It's very important to us that newcomers get the most out of these guides. 😄

**Comment by patoroco** [comment]
Checking this PR, as it looks like the `step6.png` is broken nowadays

**Comment by daviddenton** [comment]
ah - will fix. Thanks again! : )

**Comment by daviddenton** [comment]
Fixed!

**Pull request merged**
