### PR TITLE
Add zoneId, zoneOffset, and locale as default mappings

### LINKED ISSUE #720: Additional Standard Mappings
I'd like to propose additional standard mappings to `AutoMappingConfiguration`.

- java.util.Locale
- java.time.ZoneId
- java.time.ZoneOffset

I can follow up with a PR if accepted.  Thoughts?

### PR DESCRIPTION
**Pull request by oharaandrew314**
Closes #720

### CODE REVIEW

**Comment by daviddenton** [comment]
👍

**Comment by daviddenton** [comment]
@oharaandrew314 We've just upgraded in a project to the version with this change and there seems to be a problem with the mapping of Locale - we're not sure if mapping a locale to a language tag is the correct thing to be doing. Can you provide more details about this?

**Comment by oharaandrew314** [comment]
Are you able to share some details about the error?

**Comment by daviddenton** [comment]
sure - we're deserialising "pl_PL" - which is a supported locale as per this: https://www.localeplanet.com/icu/pl-PL/index.html

The new mapping causes this value to be deserialised as a blank string.

**Comment by oharaandrew314** [comment]
The java locale on that page should be `pl-PL`, but I'll see if I can get it to support the hyphenated form.

**Comment by daviddenton** [comment]
that's the strange thing - presumably the wire format should not be the java version? Although TBF I think the -/_ is irrelevant. Not sure! 😂

**Comment by oharaandrew314** [comment]
@daviddenton I did some research, and it seems like the hyphenated format is the [ISO ](https://en.wikipedia.org/wiki/ISO_639_macrolanguage) standard, and the underscored format is  [IETF ](https://en.wikipedia.org/wiki/IETF_language_tag) standard.  Java can only parse the IETF standard, so that's why the hyphenated locale cannot be parsed.

Apparently supporting both isn't as simple as replacing the `-` with a `_` because there are corner cases, and even if we added apache-commons `LangUtils` as a core dependency to parse the ISO format--doubt we want that--then we would still have to choose just one format to serialize to.

I think we should leave this as-is.  Although, perhaps a lens failure should be thrown rather than return an empty locale.

**Comment by oharaandrew314** [comment]
Sorry for all the edits; I keep getting the hyphen and underscore mixed up.

**Pull request merged**
