### PR TITLE
Convert project from buildSrcVersions to refreshVersions

### PR DESCRIPTION
**Pull request by jmfayard**
Hello friends,

Now I have a release of refreshVersions that contains again the task buildSrcVersions

The way it now works is 
- you run the task `:buildSrcVersions` only when you add a new dependencies
- the versions are stored in the file `versions.properties`
- run the task `:refreshVersions` to look up for updates then edit `versions.properties`

https://github.com/jmfayard/refreshVersions

Here is a build scan of the exact dependencies that were there before my changes

 https://scans.gradle.com/s/jzfoau7qkhxm4/dependencies?expandAll

As far as I can see, I changed exactly nothing in the version numbers

### CODE REVIEW

**Comment by daviddenton** [comment]
This looks awesome! Just one thing - can you rebase your fork so we get the up-to-date versions that we're currently shipping with all the libs? There might be another module (http4k-format-klaxon) as well which I added at the weekend.. 😄

**Comment by daviddenton** [comment]
Also - saw the comment about the "stable version" of the plugin. Is that very far off being released?

**Comment by daviddenton** [comment]
Idea: Not sure how you checked for no dependency changes - did you run “gradle dependencies” and compare the output?

**Comment by jmfayard** [comment]
> Idea: Not sure how you checked for no dependency changes - did you run “gradle dependencies” and compare the output?

Before the PR, I have run `$ ./gradlew dependencies --scan` which gives the same output but I can search into it. 
See https://scans.gradle.com/s/jzfoau7qkhxm4/dependencies?expandAll
I have compared that with the versions from versions.properties

> Also - saw the comment about the "stable version" of the plugin. Is that very far off being released?

I hope in a couple of weeks but no promise :)

> This looks awesome! Just one thing - can you rebase your fork so we get the up-to-date versions that we're currently shipping with all the libs? 😄

Do you mean rebase from the branch `aws-direct-invocation` ?
If yes, I can do that!

**Comment by daviddenton** [comment]
Rebase from master - not that random branch with WIP on it… :)

Thanks!

/dave

**Comment by jmfayard** [comment]
done @daviddenton

**Comment by daviddenton** [comment]
Thanks again for this! 😄

**Pull request merged**
